public class compass{
    protected int[] Events;
    protected bool eventMatch = false;
    //public ? audio;

//verifies if the player inputs match with the music rythm
//remember to put in thread
protected void verifyEventMatch(){
        if //(info taken from User class == listed event time){
            eventMatch = true;
        }
        else{
            eventMatch = false;
        }
    }
}